apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: alembic-preprocessing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: preprocessing
    spec:
      containers:
        - name: alembic-preprocessing
          image: macrintr/alembic-preprocessing
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "python sqs_subscriber.py alembic-preprocessing"]
          volumeMounts:
          - name: secrets
            mountPath: "/root/.cloudvolume/secrets"
            readOnly: true
          resources:
            requests:
              memory: 3Gi
      volumes:
      - name: secrets
        secret:
          secretName: secrets